-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 16:42:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`rooms` (
  `number` INT NOT NULL,
  `floor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`cleaningstuff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`cleaningstuff` (
  `idcleaningstuff` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rooms_number` INT NOT NULL,
  PRIMARY KEY (`idcleaningstuff`),
  INDEX `fk_cleaningstuff_rooms1_idx` (`rooms_number` ASC) VISIBLE,
  CONSTRAINT `fk_cleaningstuff_rooms1`
    FOREIGN KEY (`rooms_number`)
    REFERENCES `hotel`.`rooms` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`guests` (
  `idguests` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rooms_number` INT NOT NULL,
  PRIMARY KEY (`idguests`),
  INDEX `fk_guests_rooms_idx` (`rooms_number` ASC) VISIBLE,
  CONSTRAINT `fk_guests_rooms`
    FOREIGN KEY (`rooms_number`)
    REFERENCES `hotel`.`rooms` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`pools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`pools` (
  `poolid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`poolid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`restaurants` (
  `id` INT NOT NULL,
  `capacity` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`pools_has_cleaningstuff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`pools_has_cleaningstuff` (
  `pools_poolid` INT NOT NULL,
  `cleaningstuff_idcleaningstuff` INT NOT NULL,
  PRIMARY KEY (`pools_poolid`, `cleaningstuff_idcleaningstuff`),
  INDEX `fk_pools_has_cleaningstuff_cleaningstuff1_idx` (`cleaningstuff_idcleaningstuff` ASC) VISIBLE,
  INDEX `fk_pools_has_cleaningstuff_pools1_idx` (`pools_poolid` ASC) VISIBLE,
  CONSTRAINT `fk_pools_has_cleaningstuff_pools1`
    FOREIGN KEY (`pools_poolid`)
    REFERENCES `hotel`.`pools` (`poolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pools_has_cleaningstuff_cleaningstuff1`
    FOREIGN KEY (`cleaningstuff_idcleaningstuff`)
    REFERENCES `hotel`.`cleaningstuff` (`idcleaningstuff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`cleaningstuff_has_restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`cleaningstuff_has_restaurants` (
  `cleaningstuff_idcleaningstuff` INT NOT NULL,
  `restaurants_id` INT NOT NULL,
  PRIMARY KEY (`cleaningstuff_idcleaningstuff`, `restaurants_id`),
  INDEX `fk_cleaningstuff_has_restaurants_restaurants1_idx` (`restaurants_id` ASC) VISIBLE,
  INDEX `fk_cleaningstuff_has_restaurants_cleaningstuff1_idx` (`cleaningstuff_idcleaningstuff` ASC) VISIBLE,
  CONSTRAINT `fk_cleaningstuff_has_restaurants_cleaningstuff1`
    FOREIGN KEY (`cleaningstuff_idcleaningstuff`)
    REFERENCES `hotel`.`cleaningstuff` (`idcleaningstuff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cleaningstuff_has_restaurants_restaurants1`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `hotel`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
